import { Produce } from './types';

export const MOCK_PRODUCE: Produce[] = [
  {
    id: '1',
    name: 'Organic Tomatoes',
    price: 40,
    unit: 'kg',
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&q=80&w=800',
    farmerId: 'f1',
    farmerName: 'Rajesh Kumar',
    location: 'Mysuru, Karnataka',
    description: 'Freshly harvested vine-ripened organic tomatoes. No pesticides used.',
    stock: 50,
  },
  {
    id: '2',
    name: 'Alphonso Mangoes',
    price: 600,
    unit: 'dozen',
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&q=80&w=800',
    farmerId: 'f2',
    farmerName: 'Suresh Patil',
    location: 'Ratnagiri, Maharashtra',
    description: 'Premium quality Ratnagiri Alphonso mangoes. Naturally ripened.',
    stock: 20,
  },
  {
    id: '3',
    name: 'Basmati Rice',
    price: 120,
    unit: 'kg',
    category: 'Grains',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=800',
    farmerId: 'f3',
    farmerName: 'Gurpreet Singh',
    location: 'Amritsar, Punjab',
    description: 'Long-grain aromatic Basmati rice from the fields of Punjab.',
    stock: 100,
  },
  {
    id: '4',
    name: 'Fresh Carrots',
    price: 30,
    unit: 'kg',
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&q=80&w=800',
    farmerId: 'f1',
    farmerName: 'Rajesh Kumar',
    location: 'Mysuru, Karnataka',
    description: 'Sweet and crunchy carrots, perfect for salads and juices.',
    stock: 40,
  },
  {
    id: '5',
    name: 'Farm Fresh Milk',
    price: 60,
    unit: 'litre',
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1550583724-125581f77833?auto=format&fit=crop&q=80&w=800',
    farmerId: 'f4',
    farmerName: 'Lakshmi Devi',
    location: 'Chittoor, Andhra Pradesh',
    description: 'Pure, unadulterated cow milk delivered fresh from the farm.',
    stock: 30,
  },
  {
    id: '6',
    name: 'Purple Brinjal',
    price: 35,
    unit: 'kg',
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&q=80&w=800',
    farmerId: 'f1',
    farmerName: 'Rajesh Kumar',
    location: 'Mysuru, Karnataka',
    description: 'Fresh and tender purple brinjals, perfect for bharta or curries.',
    stock: 60,
  },
  {
    id: '7',
    name: 'Green Chillies',
    price: 80,
    unit: 'kg',
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1588252303782-cb80119abd6d?auto=format&fit=crop&q=80&w=800',
    farmerId: 'f5',
    farmerName: 'Anil Reddy',
    location: 'Guntur, Andhra Pradesh',
    description: 'Spicy and fresh green chillies from the fields of Guntur.',
    stock: 25,
  },
  {
    id: '8',
    name: 'French Beans',
    price: 55,
    unit: 'kg',
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1550072041-8703338b34b1?auto=format&fit=crop&q=80&w=800',
    farmerId: 'f1',
    farmerName: 'Rajesh Kumar',
    location: 'Mysuru, Karnataka',
    description: 'Crispy and fresh French beans, rich in fiber.',
    stock: 35,
  },
  {
    id: '9',
    name: 'Red Onions',
    price: 25,
    unit: 'kg',
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1508747703725-719777637510?auto=format&fit=crop&q=80&w=800',
    farmerId: 'f6',
    farmerName: 'Vinayak Rao',
    location: 'Nashik, Maharashtra',
    description: 'High-quality Nashik onions, known for their sharp flavor.',
    stock: 200,
  },
  {
    id: '10',
    name: 'Fresh Spinach',
    price: 20,
    unit: 'bunch',
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&q=80&w=800',
    farmerId: 'f1',
    farmerName: 'Rajesh Kumar',
    location: 'Mysuru, Karnataka',
    description: 'Nutritious and leafy green spinach, harvested daily.',
    stock: 45,
  },
  {
    id: '11',
    name: 'Desi Ghee',
    price: 750,
    unit: 'kg',
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1631451095765-2c91616fc9e6?auto=format&fit=crop&q=80&w=800',
    farmerId: 'f4',
    farmerName: 'Lakshmi Devi',
    location: 'Chittoor, Andhra Pradesh',
    description: 'Traditional bilona method desi ghee made from cow milk.',
    stock: 15,
  },
  {
    id: '12',
    name: 'Robusta Bananas',
    price: 60,
    unit: 'dozen',
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1571771894821-ad9902535aa4?auto=format&fit=crop&q=80&w=800',
    farmerId: 'f7',
    farmerName: 'Somanna Gowda',
    location: 'Chamarajanagar, Karnataka',
    description: 'Sweet and energy-packed Robusta bananas, naturally ripened.',
    stock: 40,
  },
  {
    id: '13',
    name: 'Red Pomegranate',
    price: 180,
    unit: 'kg',
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1615485500704-8e990f9900f7?auto=format&fit=crop&q=80&w=800',
    farmerId: 'f8',
    farmerName: 'Bhaskar Rao',
    location: 'Anantapur, Andhra Pradesh',
    description: 'Juicy and ruby-red pomegranate seeds, rich in antioxidants.',
    stock: 30,
  },
  {
    id: '14',
    name: 'Green Seedless Grapes',
    price: 120,
    unit: 'kg',
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1537640538966-79f369b41f8f?auto=format&fit=crop&q=80&w=800',
    farmerId: 'f6',
    farmerName: 'Vinayak Rao',
    location: 'Nashik, Maharashtra',
    description: 'Sweet and crunchy seedless green grapes from Nashik vineyards.',
    stock: 50,
  },
  {
    id: '15',
    name: 'Organic Papaya',
    price: 45,
    unit: 'kg',
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1526318896980-cf78c088247c?auto=format&fit=crop&q=80&w=800',
    farmerId: 'f9',
    farmerName: 'Meena Kumari',
    location: 'Coimbatore, Tamil Nadu',
    description: 'Farm-fresh sweet papaya, great for digestion and skin.',
    stock: 25,
  },
  {
    id: '16',
    name: 'Kiran Watermelon',
    price: 25,
    unit: 'kg',
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&q=80&w=800',
    farmerId: 'f10',
    farmerName: 'Ramesh Chennithala',
    location: 'Palakkad, Kerala',
    description: 'Refreshing and sweet Kiran watermelon, perfect for summer.',
    stock: 80,
  },
  {
    id: '17',
    name: 'Custard Apple (Sitaphal)',
    price: 150,
    unit: 'kg',
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1595475253541-5945ee5c2fe4?auto=format&fit=crop&q=80&w=800',
    farmerId: 'f11',
    farmerName: 'Savitri Bai',
    location: 'Beed, Maharashtra',
    description: 'Creamy and sweet Sitaphal, harvested at peak ripeness.',
    stock: 15,
  }
];
